#!/usr/bin/env node
/**
 * Brand Book Setup Script
 *
 * Run this after answering all questions in CLAUDE.md.
 * Pass answers as a JSON object (Claude will generate the call).
 *
 * Usage (Claude runs this):
 *   node setup.js --config '{ ...answers as JSON... }'
 *
 * Or run interactively:
 *   node setup.js
 */

const fs   = require('fs');
const path = require('path');
const readline = require('readline');

// ─── Helper ──────────────────────────────────────────────────────────────────

function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return [parseInt(h.slice(0,2),16), parseInt(h.slice(2,4),16), parseInt(h.slice(4,6),16)];
}

function contrastTextColor(hex) {
  const [r,g,b] = hexToRgb(hex);
  const lum = (0.299*r + 0.587*g + 0.114*b) / 255;
  return lum > 0.55 ? '#000000' : '#FFFFFF';
}

// ─── Template ────────────────────────────────────────────────────────────────

function buildBrandJs(c) {
  const primaryColors = c.primaryColors.map(col => {
    const text = col.textColor || contrastTextColor(col.hex);
    return `      { name: "${col.name}", hex: "${col.hex}", textColor: "${text}" }`;
  }).join(',\n');

  const secondaryColors = (c.secondaryColors || []).map(col => {
    const text = col.textColor || contrastTextColor(col.hex);
    const outline = col.hex === '#FFFFFF' || col.hex === '#F3F3F3' || col.hex.toLowerCase() === '#ffffff'
      ? `, outline: "1px solid #DADADA"` : '';
    return `      { name: "${col.name}", hex: "${col.hex}", textColor: "${text}"${outline} }`;
  }).join(',\n');

  const fonts = c.fonts.map(f => {
    const fmt = f.file.endsWith('.otf') ? 'opentype'
              : f.file.endsWith('.ttf') ? 'truetype'
              : f.file.endsWith('.woff2') ? 'woff2'
              : f.file.endsWith('.woff') ? 'woff' : 'truetype';
    return `      { family: "${f.family}", weight: "${f.weight}", file: "${f.file}" }`;
  }).join(',\n');

  const navGroups = buildNav(c.sections || ['logo', 'color', 'typography']);

  return `/* ─────────────────────────────────────────────────────────────────
   ${c.clientName} Brand Configuration
   Single source of truth for tokens, typography, color data, and nav.
   Generated by setup.js — edit here, not in index.html directly.
───────────────────────────────────────────────────────────────── */
const BRAND = {

  meta: {
    client:           "${c.clientName}",
    nameLine1:        "${c.nameLine1 || c.clientName}",
    nameLine2:        "${c.nameLine2 || ''}",
    title:            "${c.documentTitle || 'Brand guidelines'}",
    version:          "${c.version || 'Version 1.0'}",
    date:             "${c.date || ''}",
    preparedBy:       "${c.preparedBy || ''}",
    sidebarLogoImage: "${c.logoDark || 'images/logos/logo-dark.svg'}",
    coverSealImage:   "${c.logoMark || 'images/logos/logo-mark.svg'}",
  },

  /* ── Type specimen copy ──────────────────────────────────────── */
  specimens: {
    display96:  "${c.specimen96 || c.clientName}",
    display73:  "${c.specimen73 || ''}",
    display64:  "${c.specimen64 || ''}",
    display48:  "${c.specimen48 || ''}",
    headline42: "${c.specimen42 || ''}",
    headline32: "${c.specimen32 || ''}",
    headline24: "${c.specimenBody || ''}",
    headline21: "${c.specimenStat || ''}",
    body18:     "${c.bodyLong || ''}",
    body16:     "${c.bodyLong || ''}",
    body14:     "${c.bodyLong || ''}",
    body12:     "${c.bodyShort || ''}",
    sentence:   "${c.bodyShort || ''}",
  },

  /* ── CSS custom properties ────────────────────────────────────── */
  tokens: {
${buildTokens(c.primaryColors, c.secondaryColors)}  },

  /* ── Font faces ──────────────────────────────────────────────── */
  typography: {
    fonts: [
${fonts}
    ],
  },

  /* ── Color palettes ──────────────────────────────────────────── */
  colors: {
    primary: [
${primaryColors}
    ],
    secondary: [
${secondaryColors}
    ],
  },

  /* ── Navigation structure ─────────────────────────────────────── */
  nav: [
${navGroups}
  ],
};


/* ─────────────────────────────────────────────────────────────────
   Initialisation
───────────────────────────────────────────────────────────────── */
(function init() {
  injectTokens();
  injectFonts();
  renderNav();
  renderPalette("primary-palette-grid",   BRAND.colors.primary,   384);
  renderPalette("secondary-palette-grid", BRAND.colors.secondary, 336);
  renderCoverMeta();
  renderContent();
})();
`;
}

function buildTokens(primary, secondary) {
  const all = [...(primary || []), ...(secondary || [])];
  return all.map(c => {
    const key = c.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    return `    "${key}": "${c.hex}",`;
  }).join('\n') + '\n';
}

function buildNav(sections) {
  const groups = [];

  if (sections.includes('logo')) {
    groups.push(`    {
      group: "Logo &amp; mark",
      items: [
        { label: "Full logo",           id: "logo-horizontal" },
        { label: "Stacked logo",        id: "logo-stacked" },
        { label: "Logo mark",           id: "h-logo-mark" },
        { label: "Avatar &amp; favicon", id: "logo-avatar" },
        { label: "What to avoid",       id: "logo-avoid" },
      ],
    }`);
  }

  if (sections.includes('color')) {
    groups.push(`    {
      group: "Color",
      items: [
        { label: "Introduction",                   id: "color-intro" },
        { label: "Primary palette",                id: "primary-palette" },
        { label: "Secondary palette",              id: "secondary-palette" },
        { label: "Combinations &amp; accessibility", id: "color-combinations" },
        { label: "Color pathways",                 id: "color-pathways" },
      ],
    }`);
  }

  if (sections.includes('typography')) {
    groups.push(`    {
      group: "Typography",
      items: [
        { label: "Introduction", id: "type-intro" },
        {
          label: "Display &amp; Body", id: "fg-overview",
          groupId: "nav-fg-group", subId: "nav-fg-sub",
          children: [
            { label: "Overview",      id: "fg-overview" },
            { label: "Usage",         id: "fg-usage" },
            { label: "Type specimen", id: "fg-specimen" },
            { label: "Size &amp; scale", id: "fg-scale" },
          ],
        },
        { label: "Google fallback",  id: "google-fallback" },
        { label: "System fallback",  id: "type-fallback" },
        { label: "What to avoid",    id: "type-avoid" },
      ],
    }`);
  }

  if (sections.includes('photography')) {
    groups.push(`    {
      group: "Photography",
      items: [
        { label: "Introduction", id: "photo-intro" },
        { label: "Examples",     id: "photo-examples" },
        { label: "Dos",          id: "photo-dos" },
        { label: "Don'ts",       id: "photo-donts" },
      ],
    }`);
  }

  if (sections.includes('applications')) {
    groups.push(`    {
      group: "Applications",
      items: [
        { label: "Introduction", id: "app-intro" },
      ],
    }`);
  }

  return groups.join(',\n') + ',';
}

// ─── Interactive mode ─────────────────────────────────────────────────────────

async function ask(rl, question) {
  return new Promise(resolve => rl.question(question, resolve));
}

async function askColors(rl, label) {
  console.log(`\n${label}`);
  console.log('Enter each color on its own line as: Name, #HEX  (e.g. "Primary Blue, #1CACFF")');
  console.log('Press Enter on a blank line when done.\n');
  const colors = [];
  while (true) {
    const line = (await ask(rl, '  Color: ')).trim();
    if (!line) break;
    const [name, hex] = line.split(',').map(s => s.trim());
    if (name && hex) colors.push({ name, hex });
    else console.log('  (Skipped — use format: Name, #HEX)');
  }
  return colors;
}

async function askFonts(rl) {
  console.log('\nFONTS');
  console.log('Enter each font on its own line as: Family, weight, filename');
  console.log('Examples:');
  console.log('  PolySans, 100 900, fonts/PolySansTrial-Median.otf');
  console.log('  Inter, 400, fonts/Inter-VariableFont_opsz,wght.ttf');
  console.log('Press Enter on a blank line when done.\n');
  const fonts = [];
  while (true) {
    const line = (await ask(rl, '  Font: ')).trim();
    if (!line) break;
    const parts = line.split(',').map(s => s.trim());
    if (parts.length >= 3) {
      fonts.push({ family: parts[0], weight: parts[1], file: parts[2] });
    } else {
      console.log('  (Skipped — need: Family, weight, filename)');
    }
  }
  return fonts;
}

async function interactive() {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  console.log('\n══════════════════════════════════════════');
  console.log('  Brand Book Setup');
  console.log('══════════════════════════════════════════\n');

  const config = {};

  // Group 1 — Client basics
  console.log('── CLIENT BASICS ──────────────────────────\n');
  config.clientName     = (await ask(rl, 'Client company name: ')).trim();
  config.nameLine1      = config.clientName;
  config.documentTitle  = (await ask(rl, 'Document title [Brand guidelines]: ')).trim() || 'Brand guidelines';
  config.version        = (await ask(rl, 'Version [Version 1.0]: ')).trim() || 'Version 1.0';
  config.date           = (await ask(rl, 'Date (e.g. June 2026): ')).trim();
  config.preparedBy     = (await ask(rl, 'Prepared by: ')).trim();

  // Group 2 — Colors
  console.log('\n── COLORS ─────────────────────────────────');
  config.primaryColors   = await askColors(rl, 'PRIMARY COLORS');
  config.secondaryColors = await askColors(rl, 'SECONDARY COLORS (leave blank if none)');

  // Group 3 — Fonts
  config.fonts = await askFonts(rl);

  // Group 4 — Logos
  console.log('\n── LOGOS ──────────────────────────────────\n');
  config.logoDark  = (await ask(rl, 'Dark logo path (for light backgrounds): ')).trim();
  config.logoLight = (await ask(rl, 'Light logo path (for bright color backgrounds): ')).trim();
  config.logoWhite = (await ask(rl, 'White logo path (for dark backgrounds): ')).trim();
  config.logoMark  = (await ask(rl, 'Logo mark/icon path (cover page seal): ')).trim();

  // Group 5 — Specimens
  console.log('\n── TYPE SPECIMENS ─────────────────────────\n');
  config.specimen96  = (await ask(rl, 'Largest display word (e.g. company name): ')).trim();
  config.specimen73  = (await ask(rl, '2–3 word phrase: ')).trim();
  config.specimen64  = (await ask(rl, 'Short tagline: ')).trim();
  config.specimen48  = (await ask(rl, 'Product or service name: ')).trim();
  config.specimen42  = (await ask(rl, 'Headline example: ')).trim();
  config.specimen32  = (await ask(rl, 'Sub-headline example: ')).trim();
  config.bodyShort   = (await ask(rl, 'One-sentence company description: ')).trim();
  config.bodyLong    = (await ask(rl, 'Two–three sentence body copy: ')).trim();

  // Group 6 — Sections
  console.log('\n── SECTIONS ────────────────────────────────');
  console.log('Available: logo, color, typography, photography, applications, iconography');
  const sectionsInput = (await ask(rl, 'Which to include? [logo, color, typography]: ')).trim();
  config.sections = sectionsInput
    ? sectionsInput.split(',').map(s => s.trim().toLowerCase())
    : ['logo', 'color', 'typography'];

  rl.close();

  // Write brand.js
  const output = buildBrandJs(config);
  const dest = path.join(__dirname, 'brand.js');
  fs.writeFileSync(dest, output, 'utf8');

  console.log('\n✓ brand.js written successfully.');
  console.log('\nNext steps:');
  console.log('  1. Place logo files in images/logos/');
  console.log('  2. Place font files in fonts/');
  console.log('  3. Open index.html in a browser to preview');
  console.log('  4. Ask Claude to review and fill in the section copy\n');
}

// ─── JSON config mode (for Claude to call directly) ──────────────────────────

function fromArgs() {
  const idx = process.argv.indexOf('--config');
  if (idx === -1) return null;
  try {
    return JSON.parse(process.argv[idx + 1]);
  } catch (e) {
    console.error('Error parsing --config JSON:', e.message);
    process.exit(1);
  }
}

// ─── Entry ───────────────────────────────────────────────────────────────────

const argConfig = fromArgs();
if (argConfig) {
  const output = buildBrandJs(argConfig);
  const dest = path.join(__dirname, 'brand.js');
  fs.writeFileSync(dest, output, 'utf8');
  console.log('brand.js written from --config.');
} else {
  interactive().catch(err => { console.error(err); process.exit(1); });
}
